name: project_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  image_picker: ^1.1.2
  shared_preferences: ^2.2.2 
  carousel_slider: ^4.2.1
  intl: ^0.20.2
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  google_maps_flutter: ^2.9.0
  google_maps_flutter_web: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
   

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/

fonts:
    - family: Sarabun
      fonts:
        - asset: lib/assets/fonts/Sarabun-Bold.ttf
